# Generated by Django 5.2.9 on 2025-12-26 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='commpleted',
            new_name='completed',
        ),
        migrations.CreateModel(
            name='Dador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('nif', models.CharField(max_length=12)),
                ('genero', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefone', models.CharField(max_length=9)),
                ('tipo', models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('O+', 'O positivo'), ('O-', 'O negativo')], default='O-', max_length=3)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimaDoacao', models.DateField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadores', to='myfarmacia.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=9)),
                ('morada', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=8)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitais', to='myfarmacia.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listaPedidos', to='myfarmacia.banco')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listaPedido', to='myfarmacia.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('B+', 'B positivo'), ('B-', 'B negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('O+', 'O positivo'), ('O-', 'O negativo')], default='O-', max_length=3)),
                ('componente', models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'plasma')], default='sangue', max_length=20)),
                ('quantidade', models.IntegerField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhaPedido', to='myfarmacia.banco')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens', to='myfarmacia.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PostoRecolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=8)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='myfarmacia.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('componente', models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'plasma')], default='sangue', max_length=20)),
                ('valido', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='myfarmacia.banco')),
                ('dador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doacoes', to='myfarmacia.dador')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='myfarmacia.postorecolha')),
            ],
        ),
    ]
