# Generated by Django 6.0 on 2025-12-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0002_perfilhospital_perfilposto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dador',
            old_name='tipo',
            new_name='tipo_sangue',
        ),
    ]
