# Generated by Django 6.0 on 2025-12-27 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0003_rename_tipo_dador_tipo_sangue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfarmacia.dador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
