# Generated by Django 6.0 on 2025-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0006_alter_dador_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dador',
            name='nif',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='dador',
            name='telefone',
            field=models.CharField(max_length=9),
        ),
    ]
