# Generated by Django 6.0 on 2025-12-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0008_alter_dador_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dador',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dador',
            name='nif',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='componente',
            field=models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'Plasma')], default='sangue', max_length=20),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='linhapedido',
            name='componente',
            field=models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'Plasma')], default='sangue', max_length=20),
        ),
    ]
