# Generated by Django 6.0 on 2025-12-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0009_alter_dador_genero_alter_dador_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='componente',
            field=models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'Plasma'), ('plaquetas', 'Plaquetas')], default='sangue', max_length=20),
        ),
        migrations.AlterField(
            model_name='linhapedido',
            name='componente',
            field=models.CharField(choices=[('sangue', 'Sangue'), ('globulos', 'Globulos Vermelhos'), ('plasma', 'Plasma'), ('plaquetas', 'Plaquetas')], default='sangue', max_length=20),
        ),
    ]
