# Generated by Django 5.2.9 on 2025-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0010_alter_doacao_componente_alter_linhapedido_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
