# Generated by Django 5.2.9 on 2025-12-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0011_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='ativo', max_length=20),
        ),
    ]
