# Generated by Django 5.2.9 on 2025-12-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarmacia', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='myfarmacia.pedido'),
        ),
    ]
